server:
  port: 8002
spring:
  datasource:
    url: jdbc:mysql://182.92.149.21:3306/gj?useUnicode=true&characterEncoding=utf8
    username: root
    password: FDab7185?
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

    #jdbc:mysql:localhost:3306/blog?useUnicode=true&characterEncoding=utf8
#  mvc:
#    pathmatch:
#      matching-strategy=ANT_PATH_MATCHER
